<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCz8oxBH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCz8oxBH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCz8oxBH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCz8oxBH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCz8oxBH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cz8oxBH',
    'container.build_id' => '672a630e',
    'container.build_time' => 1674555751,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCz8oxBH');
